export const MAJOR_ARCANA = [
  {
    number: 0,
    roman: "0",
    name: "愚者",
    en: "THE FOOL",
    symbol: "✦",
    keywords: ["启程", "自由", "信任"],
    upright: "新的旅程正在展开。保持好奇与开放，允许自己在尚未掌握全部答案时迈出第一步。",
    reversed: "冲动、逃避准备或对风险视而不见。此刻需要把自由建立在基本判断之上。",
    advice: "为想尝试的方向设一个最小可行步骤，同时保留回头检查的空间。",
  },
  {
    number: 1,
    roman: "I",
    name: "魔术师",
    en: "THE MAGICIAN",
    symbol: "∞",
    keywords: ["创造", "意志", "资源"],
    upright: "你已经拥有让事情启动的关键资源，清晰的意图与专注行动会把可能性变成现实。",
    reversed: "能力被分散、表达与行动不一致，或有人在过度包装事实。先厘清真实意图。",
    advice: "盘点手边已经拥有的人、信息与工具，只选择一个目标集中推进。",
  },
  {
    number: 2,
    roman: "II",
    name: "女祭司",
    en: "THE HIGH PRIESTESS",
    symbol: "☾",
    keywords: ["直觉", "沉静", "未知"],
    upright: "答案尚未完全显露，安静观察比急于定论更有价值。你的直觉正在捕捉细微信号。",
    reversed: "忽略内在感受、信息被遮蔽，或焦虑让直觉失真。需要区分预感与猜测。",
    advice: "暂缓一次仓促回应，记录事实与感受，等两者都清晰后再决定。",
  },
  {
    number: 3,
    roman: "III",
    name: "皇后",
    en: "THE EMPRESS",
    symbol: "❀",
    keywords: ["丰盛", "滋养", "生长"],
    upright: "耐心投入正在孕育可见成果。关系、创意或生活需要被温柔而持续地照料。",
    reversed: "过度付出、自我忽视或成长节奏被催促。丰盛感需要先从照顾自己恢复。",
    advice: "把时间留给真正需要培育的人与事，并为自己设下同等重要的照顾计划。",
  },
  {
    number: 4,
    roman: "IV",
    name: "皇帝",
    en: "THE EMPEROR",
    symbol: "△",
    keywords: ["秩序", "边界", "担当"],
    upright: "清晰规则、稳定结构与可靠执行会带来安全感。现在适合承担主导责任。",
    reversed: "控制过度、规则僵化，或缺少必要边界。权威与责任之间出现了失衡。",
    advice: "明确不可妥协的底线，同时给他人留下参与和反馈的空间。",
  },
  {
    number: 5,
    roman: "V",
    name: "教皇",
    en: "THE HIEROPHANT",
    symbol: "✥",
    keywords: ["传统", "学习", "承诺"],
    upright: "成熟经验、共同价值或一位可信赖的引导者能帮助你建立稳定路径。",
    reversed: "旧有标准已无法完整回答当前问题，需要辨认哪些规则值得保留、哪些应被更新。",
    advice: "向可靠的人或体系学习，但用自己的价值观做最后一次筛选。",
  },
  {
    number: 6,
    roman: "VI",
    name: "恋人",
    en: "THE LOVERS",
    symbol: "♡",
    keywords: ["选择", "连结", "一致"],
    upright: "重要的连结或选择正在要求你忠于真实价值。坦诚会让关系与决定变得清晰。",
    reversed: "价值冲突、沟通错位或在关键选择前犹豫。表面和谐掩盖不了内在分歧。",
    advice: "先回答“我真正重视什么”，再进行一次不回避重点的沟通。",
  },
  {
    number: 7,
    roman: "VII",
    name: "战车",
    en: "THE CHARIOT",
    symbol: "➶",
    keywords: ["推进", "自律", "方向"],
    upright: "不同力量正在被同一目标整合。坚定方向并保持节奏，就能突破当前阻力。",
    reversed: "目标摇摆、用力失衡或急于证明自己。速度正在削弱对方向的判断。",
    advice: "重新写下唯一的阶段目标，删除不服务于它的两项消耗。",
  },
  {
    number: 8,
    roman: "VIII",
    name: "力量",
    en: "STRENGTH",
    symbol: "♧",
    keywords: ["勇气", "耐心", "柔韧"],
    upright: "真正的力量来自稳定、温柔与自我信任。你能够不靠压制而驯服困难。",
    reversed: "自我怀疑、情绪耗损或把强硬误当成力量。需要先恢复内在稳定。",
    advice: "用可持续的小行动替代一次性逞强，并对自己的恐惧保持诚实。",
  },
  {
    number: 9,
    roman: "IX",
    name: "隐者",
    en: "THE HERMIT",
    symbol: "◇",
    keywords: ["独处", "求索", "内省"],
    upright: "暂时后退能看清更深层的答案。独立思考与经验沉淀比外界噪声更重要。",
    reversed: "孤立、封闭或反复思考却没有结论。独处需要有边界，也需要重新连接现实。",
    advice: "给自己一段有期限的安静时间，结束后向可信的人验证你的想法。",
  },
  {
    number: 10,
    roman: "X",
    name: "命运之轮",
    en: "WHEEL OF FORTUNE",
    symbol: "⊙",
    keywords: ["转折", "周期", "机缘"],
    upright: "局势进入新的周期，外部变化带来意料之外的窗口。灵活会放大好运。",
    reversed: "计划受阻、旧模式循环或对不可控变化产生抗拒。先找到仍可掌握的部分。",
    advice: "识别正在改变的条件，准备一个顺势方案与一个保底方案。",
  },
  {
    number: 11,
    roman: "XI",
    name: "正义",
    en: "JUSTICE",
    symbol: "⚖",
    keywords: ["真相", "平衡", "责任"],
    upright: "事实、因果与公平是当前核心。诚实面对选择的后果，会得到更稳固的结果。",
    reversed: "信息偏差、责任逃避或评价失衡。不要在证据不足时仓促定性。",
    advice: "把事实、假设和情绪分开列出，再做一次可被解释的决定。",
  },
  {
    number: 12,
    roman: "XII",
    name: "倒吊人",
    en: "THE HANGED MAN",
    symbol: "▽",
    keywords: ["暂停", "换位", "放下"],
    upright: "主动暂停能带来全新视角。暂时放下控制，并不等于失败或停滞。",
    reversed: "无意义的等待、拖延牺牲或执着于单一角度。暂停已经失去其学习价值。",
    advice: "改变一个观察角度；若仍无新信息，就为等待设下明确截止点。",
  },
  {
    number: 13,
    roman: "XIII",
    name: "死神",
    en: "DEATH",
    symbol: "✢",
    keywords: ["结束", "蜕变", "清理"],
    upright: "一个阶段正在完成，腾出的空间会允许新的形态出现。结束是转化的一部分。",
    reversed: "抗拒告别、旧模式迟迟不退，或变化被一再延后。抓紧过去正在消耗现在。",
    advice: "明确结束一件已经失效的事，并为新阶段建立一个简单仪式或标记。",
  },
  {
    number: 14,
    roman: "XIV",
    name: "节制",
    en: "TEMPERANCE",
    symbol: "≈",
    keywords: ["调和", "节奏", "修复"],
    upright: "不同需求可以通过耐心调和形成新的平衡。稳步整合比激烈突破更有效。",
    reversed: "节奏失衡、极端摇摆或恢复过程被打断。需要减少刺激，回到基本秩序。",
    advice: "选择一个最影响状态的习惯进行微调，连续维持七天再评估。",
  },
  {
    number: 15,
    roman: "XV",
    name: "恶魔",
    en: "THE DEVIL",
    symbol: "⛓",
    keywords: ["束缚", "欲望", "觉察"],
    upright: "某种依赖、恐惧或即时诱惑正在影响选择。看见锁链，才有机会松开它。",
    reversed: "你开始识别并摆脱不健康模式，但旧习惯仍可能反复拉扯。",
    advice: "说出最难承认的依赖，并移除一个最容易触发它的环境条件。",
  },
  {
    number: 16,
    roman: "XVI",
    name: "高塔",
    en: "THE TOWER",
    symbol: "ϟ",
    keywords: ["震荡", "揭示", "重建"],
    upright: "突发变化正在击穿不稳固的结构。真相虽然剧烈，却让重建成为可能。",
    reversed: "变化被压抑、危机尚在内部累积，或你正从震荡中缓慢恢复。",
    advice: "先保证基本安全与事实清楚，再决定哪些结构值得修复、哪些必须重建。",
  },
  {
    number: 17,
    roman: "XVII",
    name: "星星",
    en: "THE STAR",
    symbol: "✧",
    keywords: ["希望", "疗愈", "愿景"],
    upright: "希望正在恢复，真诚愿景会为下一段路提供方向。允许自己重新相信未来。",
    reversed: "暂时失去信心、理想与现实脱节，或修复需要比预期更长的时间。",
    advice: "把遥远愿景缩成一个本周能完成的温柔行动，让希望重新获得证据。",
  },
  {
    number: 18,
    roman: "XVIII",
    name: "月亮",
    en: "THE MOON",
    symbol: "☽",
    keywords: ["迷雾", "潜意识", "敏感"],
    upright: "信息仍然模糊，情绪与想象放大了不确定性。需要慢下来辨认真实信号。",
    reversed: "迷雾逐渐散开，隐藏情绪开始被看见；也可能代表焦虑正在扭曲判断。",
    advice: "暂不依据猜测行动，先验证一条关键信息，并照顾好睡眠与情绪。",
  },
  {
    number: 19,
    roman: "XIX",
    name: "太阳",
    en: "THE SUN",
    symbol: "☼",
    keywords: ["清晰", "活力", "喜悦"],
    upright: "局势趋向明朗，真诚表达与积极行动带来温暖成果。你可以更坦然地被看见。",
    reversed: "快乐被压力遮住、期待过高或好消息略有延迟，但核心能量仍然积极。",
    advice: "分享一个真实进展，庆祝已经发生的好事，同时调整不切实际的期待。",
  },
  {
    number: 20,
    roman: "XX",
    name: "审判",
    en: "JUDGEMENT",
    symbol: "⌁",
    keywords: ["觉醒", "召唤", "复盘"],
    upright: "过去经验正在汇聚成清晰召唤。诚实复盘后，你有机会做出不同选择。",
    reversed: "害怕评价、拒绝总结或迟迟不愿回应内在召唤。自我批判阻碍了更新。",
    advice: "写下这段经历真正教会你的三件事，然后为下一步作出明确回应。",
  },
  {
    number: 21,
    roman: "XXI",
    name: "世界",
    en: "THE WORLD",
    symbol: "◎",
    keywords: ["完成", "整合", "抵达"],
    upright: "一个重要周期趋于完整，经验、资源与身份正在被整合。你可以带着成果进入新阶段。",
    reversed: "临门一脚尚未完成、收尾被拖延，或对“完美完成”的执念阻碍交付。",
    advice: "定义完成标准，补上最后一个关键缺口，然后允许这一章正式结束。",
  },
];
