export const QUESTION_PROFILE_IDS = Object.freeze([
  "love-current",
  "love-future",
  "love-improve",
  "love-new",
  "love-truth",
  "love-self",
  "love-communication",
  "career-focus",
  "career-block",
  "career-change",
  "career-growth",
  "career-team",
  "career-balance",
  "career-opportunity",
  "wealth-state",
  "wealth-opportunity",
  "wealth-risk",
  "wealth-growth",
  "wealth-project",
  "wealth-habit",
  "wealth-resource",
  "growth-lesson",
  "growth-release",
  "growth-strength",
  "growth-heal",
  "growth-next",
  "growth-boundary",
  "growth-purpose",
  "decision-see",
  "decision-a",
  "decision-change",
  "decision-value",
  "decision-timing",
  "decision-cost",
  "decision-option",
  "daily-energy",
  "daily-focus",
  "daily-avoid",
  "daily-message",
  "daily-action",
  "daily-relationship",
  "daily-rest",
  "love-boundaries",
  "love-reciprocity",
  "love-trust",
  "love-distance",
  "love-choice",
  "love-repair",
  "love-ending",
  "love-third-party",
  "career-role-fit",
  "career-feedback",
  "career-leadership",
  "career-conflict",
  "career-burnout",
  "career-negotiation",
  "career-transition-cost",
  "career-portfolio",
  "wealth-budget",
  "wealth-debt",
  "wealth-savings",
  "wealth-investment",
  "wealth-income",
  "wealth-sharing",
  "wealth-loss",
  "wealth-purchase",
  "growth-belief",
  "growth-emotion",
  "growth-support",
  "growth-shame",
  "growth-identity",
  "growth-practice",
  "growth-forgiveness",
  "growth-help",
  "decision-evidence",
  "decision-reversible",
  "decision-stakeholders",
  "decision-pressure",
  "decision-no-choice",
  "decision-threshold",
  "decision-safety",
  "decision-commitment",
  "daily-priority",
  "daily-boundary",
  "daily-conversation",
  "daily-body",
  "daily-money",
  "daily-learning",
  "daily-finish",
  "daily-uncertainty"
]);

export const QUESTION_PROFILE_REGISTRY = Object.freeze({
  "love-current": async () => (await import("./profiles/love-current.js")).QUESTION_PROFILE,
  "love-future": async () => (await import("./profiles/love-future.js")).QUESTION_PROFILE,
  "love-improve": async () => (await import("./profiles/love-improve.js")).QUESTION_PROFILE,
  "love-new": async () => (await import("./profiles/love-new.js")).QUESTION_PROFILE,
  "love-truth": async () => (await import("./profiles/love-truth.js")).QUESTION_PROFILE,
  "love-self": async () => (await import("./profiles/love-self.js")).QUESTION_PROFILE,
  "love-communication": async () => (await import("./profiles/love-communication.js")).QUESTION_PROFILE,
  "career-focus": async () => (await import("./profiles/career-focus.js")).QUESTION_PROFILE,
  "career-block": async () => (await import("./profiles/career-block.js")).QUESTION_PROFILE,
  "career-change": async () => (await import("./profiles/career-change.js")).QUESTION_PROFILE,
  "career-growth": async () => (await import("./profiles/career-growth.js")).QUESTION_PROFILE,
  "career-team": async () => (await import("./profiles/career-team.js")).QUESTION_PROFILE,
  "career-balance": async () => (await import("./profiles/career-balance.js")).QUESTION_PROFILE,
  "career-opportunity": async () => (await import("./profiles/career-opportunity.js")).QUESTION_PROFILE,
  "wealth-state": async () => (await import("./profiles/wealth-state.js")).QUESTION_PROFILE,
  "wealth-opportunity": async () => (await import("./profiles/wealth-opportunity.js")).QUESTION_PROFILE,
  "wealth-risk": async () => (await import("./profiles/wealth-risk.js")).QUESTION_PROFILE,
  "wealth-growth": async () => (await import("./profiles/wealth-growth.js")).QUESTION_PROFILE,
  "wealth-project": async () => (await import("./profiles/wealth-project.js")).QUESTION_PROFILE,
  "wealth-habit": async () => (await import("./profiles/wealth-habit.js")).QUESTION_PROFILE,
  "wealth-resource": async () => (await import("./profiles/wealth-resource.js")).QUESTION_PROFILE,
  "growth-lesson": async () => (await import("./profiles/growth-lesson.js")).QUESTION_PROFILE,
  "growth-release": async () => (await import("./profiles/growth-release.js")).QUESTION_PROFILE,
  "growth-strength": async () => (await import("./profiles/growth-strength.js")).QUESTION_PROFILE,
  "growth-heal": async () => (await import("./profiles/growth-heal.js")).QUESTION_PROFILE,
  "growth-next": async () => (await import("./profiles/growth-next.js")).QUESTION_PROFILE,
  "growth-boundary": async () => (await import("./profiles/growth-boundary.js")).QUESTION_PROFILE,
  "growth-purpose": async () => (await import("./profiles/growth-purpose.js")).QUESTION_PROFILE,
  "decision-see": async () => (await import("./profiles/decision-see.js")).QUESTION_PROFILE,
  "decision-a": async () => (await import("./profiles/decision-a.js")).QUESTION_PROFILE,
  "decision-change": async () => (await import("./profiles/decision-change.js")).QUESTION_PROFILE,
  "decision-value": async () => (await import("./profiles/decision-value.js")).QUESTION_PROFILE,
  "decision-timing": async () => (await import("./profiles/decision-timing.js")).QUESTION_PROFILE,
  "decision-cost": async () => (await import("./profiles/decision-cost.js")).QUESTION_PROFILE,
  "decision-option": async () => (await import("./profiles/decision-option.js")).QUESTION_PROFILE,
  "daily-energy": async () => (await import("./profiles/daily-energy.js")).QUESTION_PROFILE,
  "daily-focus": async () => (await import("./profiles/daily-focus.js")).QUESTION_PROFILE,
  "daily-avoid": async () => (await import("./profiles/daily-avoid.js")).QUESTION_PROFILE,
  "daily-message": async () => (await import("./profiles/daily-message.js")).QUESTION_PROFILE,
  "daily-action": async () => (await import("./profiles/daily-action.js")).QUESTION_PROFILE,
  "daily-relationship": async () => (await import("./profiles/daily-relationship.js")).QUESTION_PROFILE,
  "daily-rest": async () => (await import("./profiles/daily-rest.js")).QUESTION_PROFILE,
  "love-boundaries": async () => (await import("./profiles/love-boundaries.js")).QUESTION_PROFILE,
  "love-reciprocity": async () => (await import("./profiles/love-reciprocity.js")).QUESTION_PROFILE,
  "love-trust": async () => (await import("./profiles/love-trust.js")).QUESTION_PROFILE,
  "love-distance": async () => (await import("./profiles/love-distance.js")).QUESTION_PROFILE,
  "love-choice": async () => (await import("./profiles/love-choice.js")).QUESTION_PROFILE,
  "love-repair": async () => (await import("./profiles/love-repair.js")).QUESTION_PROFILE,
  "love-ending": async () => (await import("./profiles/love-ending.js")).QUESTION_PROFILE,
  "love-third-party": async () => (await import("./profiles/love-third-party.js")).QUESTION_PROFILE,
  "career-role-fit": async () => (await import("./profiles/career-role-fit.js")).QUESTION_PROFILE,
  "career-feedback": async () => (await import("./profiles/career-feedback.js")).QUESTION_PROFILE,
  "career-leadership": async () => (await import("./profiles/career-leadership.js")).QUESTION_PROFILE,
  "career-conflict": async () => (await import("./profiles/career-conflict.js")).QUESTION_PROFILE,
  "career-burnout": async () => (await import("./profiles/career-burnout.js")).QUESTION_PROFILE,
  "career-negotiation": async () => (await import("./profiles/career-negotiation.js")).QUESTION_PROFILE,
  "career-transition-cost": async () => (await import("./profiles/career-transition-cost.js")).QUESTION_PROFILE,
  "career-portfolio": async () => (await import("./profiles/career-portfolio.js")).QUESTION_PROFILE,
  "wealth-budget": async () => (await import("./profiles/wealth-budget.js")).QUESTION_PROFILE,
  "wealth-debt": async () => (await import("./profiles/wealth-debt.js")).QUESTION_PROFILE,
  "wealth-savings": async () => (await import("./profiles/wealth-savings.js")).QUESTION_PROFILE,
  "wealth-investment": async () => (await import("./profiles/wealth-investment.js")).QUESTION_PROFILE,
  "wealth-income": async () => (await import("./profiles/wealth-income.js")).QUESTION_PROFILE,
  "wealth-sharing": async () => (await import("./profiles/wealth-sharing.js")).QUESTION_PROFILE,
  "wealth-loss": async () => (await import("./profiles/wealth-loss.js")).QUESTION_PROFILE,
  "wealth-purchase": async () => (await import("./profiles/wealth-purchase.js")).QUESTION_PROFILE,
  "growth-belief": async () => (await import("./profiles/growth-belief.js")).QUESTION_PROFILE,
  "growth-emotion": async () => (await import("./profiles/growth-emotion.js")).QUESTION_PROFILE,
  "growth-support": async () => (await import("./profiles/growth-support.js")).QUESTION_PROFILE,
  "growth-shame": async () => (await import("./profiles/growth-shame.js")).QUESTION_PROFILE,
  "growth-identity": async () => (await import("./profiles/growth-identity.js")).QUESTION_PROFILE,
  "growth-practice": async () => (await import("./profiles/growth-practice.js")).QUESTION_PROFILE,
  "growth-forgiveness": async () => (await import("./profiles/growth-forgiveness.js")).QUESTION_PROFILE,
  "growth-help": async () => (await import("./profiles/growth-help.js")).QUESTION_PROFILE,
  "decision-evidence": async () => (await import("./profiles/decision-evidence.js")).QUESTION_PROFILE,
  "decision-reversible": async () => (await import("./profiles/decision-reversible.js")).QUESTION_PROFILE,
  "decision-stakeholders": async () => (await import("./profiles/decision-stakeholders.js")).QUESTION_PROFILE,
  "decision-pressure": async () => (await import("./profiles/decision-pressure.js")).QUESTION_PROFILE,
  "decision-no-choice": async () => (await import("./profiles/decision-no-choice.js")).QUESTION_PROFILE,
  "decision-threshold": async () => (await import("./profiles/decision-threshold.js")).QUESTION_PROFILE,
  "decision-safety": async () => (await import("./profiles/decision-safety.js")).QUESTION_PROFILE,
  "decision-commitment": async () => (await import("./profiles/decision-commitment.js")).QUESTION_PROFILE,
  "daily-priority": async () => (await import("./profiles/daily-priority.js")).QUESTION_PROFILE,
  "daily-boundary": async () => (await import("./profiles/daily-boundary.js")).QUESTION_PROFILE,
  "daily-conversation": async () => (await import("./profiles/daily-conversation.js")).QUESTION_PROFILE,
  "daily-body": async () => (await import("./profiles/daily-body.js")).QUESTION_PROFILE,
  "daily-money": async () => (await import("./profiles/daily-money.js")).QUESTION_PROFILE,
  "daily-learning": async () => (await import("./profiles/daily-learning.js")).QUESTION_PROFILE,
  "daily-finish": async () => (await import("./profiles/daily-finish.js")).QUESTION_PROFILE,
  "daily-uncertainty": async () => (await import("./profiles/daily-uncertainty.js")).QUESTION_PROFILE,
});

export async function loadQuestionProfile(questionId) {
  const loader = QUESTION_PROFILE_REGISTRY[questionId];
  if (!loader) throw new Error(`Unknown QuestionProfile: ${questionId}`);
  return loader();
}
