export const QUESTION_PROFILE_IDS = Object.freeze([
  "love-current",
  "love-future",
  "love-improve",
  "love-new",
  "love-truth",
  "love-self",
  "love-communication",
  "career-focus",
  "career-block",
  "career-change",
  "career-growth",
  "career-team",
  "career-balance",
  "career-opportunity",
  "wealth-state",
  "wealth-opportunity",
  "wealth-risk",
  "wealth-growth",
  "wealth-project",
  "wealth-habit",
  "wealth-resource",
  "growth-lesson",
  "growth-release",
  "growth-strength",
  "growth-heal",
  "growth-next",
  "growth-boundary",
  "growth-purpose",
  "decision-see",
  "decision-a",
  "decision-change",
  "decision-value",
  "decision-timing",
  "decision-cost",
  "decision-option",
  "daily-energy",
  "daily-focus",
  "daily-avoid",
  "daily-message",
  "daily-action",
  "daily-relationship",
  "daily-rest",
]);

export const QUESTION_PROFILE_REGISTRY = Object.freeze({
  "love-current": async () => (await import("./profiles/love-current.js")).QUESTION_PROFILE,
  "love-future": async () => (await import("./profiles/love-future.js")).QUESTION_PROFILE,
  "love-improve": async () => (await import("./profiles/love-improve.js")).QUESTION_PROFILE,
  "love-new": async () => (await import("./profiles/love-new.js")).QUESTION_PROFILE,
  "love-truth": async () => (await import("./profiles/love-truth.js")).QUESTION_PROFILE,
  "love-self": async () => (await import("./profiles/love-self.js")).QUESTION_PROFILE,
  "love-communication": async () => (await import("./profiles/love-communication.js")).QUESTION_PROFILE,
  "career-focus": async () => (await import("./profiles/career-focus.js")).QUESTION_PROFILE,
  "career-block": async () => (await import("./profiles/career-block.js")).QUESTION_PROFILE,
  "career-change": async () => (await import("./profiles/career-change.js")).QUESTION_PROFILE,
  "career-growth": async () => (await import("./profiles/career-growth.js")).QUESTION_PROFILE,
  "career-team": async () => (await import("./profiles/career-team.js")).QUESTION_PROFILE,
  "career-balance": async () => (await import("./profiles/career-balance.js")).QUESTION_PROFILE,
  "career-opportunity": async () => (await import("./profiles/career-opportunity.js")).QUESTION_PROFILE,
  "wealth-state": async () => (await import("./profiles/wealth-state.js")).QUESTION_PROFILE,
  "wealth-opportunity": async () => (await import("./profiles/wealth-opportunity.js")).QUESTION_PROFILE,
  "wealth-risk": async () => (await import("./profiles/wealth-risk.js")).QUESTION_PROFILE,
  "wealth-growth": async () => (await import("./profiles/wealth-growth.js")).QUESTION_PROFILE,
  "wealth-project": async () => (await import("./profiles/wealth-project.js")).QUESTION_PROFILE,
  "wealth-habit": async () => (await import("./profiles/wealth-habit.js")).QUESTION_PROFILE,
  "wealth-resource": async () => (await import("./profiles/wealth-resource.js")).QUESTION_PROFILE,
  "growth-lesson": async () => (await import("./profiles/growth-lesson.js")).QUESTION_PROFILE,
  "growth-release": async () => (await import("./profiles/growth-release.js")).QUESTION_PROFILE,
  "growth-strength": async () => (await import("./profiles/growth-strength.js")).QUESTION_PROFILE,
  "growth-heal": async () => (await import("./profiles/growth-heal.js")).QUESTION_PROFILE,
  "growth-next": async () => (await import("./profiles/growth-next.js")).QUESTION_PROFILE,
  "growth-boundary": async () => (await import("./profiles/growth-boundary.js")).QUESTION_PROFILE,
  "growth-purpose": async () => (await import("./profiles/growth-purpose.js")).QUESTION_PROFILE,
  "decision-see": async () => (await import("./profiles/decision-see.js")).QUESTION_PROFILE,
  "decision-a": async () => (await import("./profiles/decision-a.js")).QUESTION_PROFILE,
  "decision-change": async () => (await import("./profiles/decision-change.js")).QUESTION_PROFILE,
  "decision-value": async () => (await import("./profiles/decision-value.js")).QUESTION_PROFILE,
  "decision-timing": async () => (await import("./profiles/decision-timing.js")).QUESTION_PROFILE,
  "decision-cost": async () => (await import("./profiles/decision-cost.js")).QUESTION_PROFILE,
  "decision-option": async () => (await import("./profiles/decision-option.js")).QUESTION_PROFILE,
  "daily-energy": async () => (await import("./profiles/daily-energy.js")).QUESTION_PROFILE,
  "daily-focus": async () => (await import("./profiles/daily-focus.js")).QUESTION_PROFILE,
  "daily-avoid": async () => (await import("./profiles/daily-avoid.js")).QUESTION_PROFILE,
  "daily-message": async () => (await import("./profiles/daily-message.js")).QUESTION_PROFILE,
  "daily-action": async () => (await import("./profiles/daily-action.js")).QUESTION_PROFILE,
  "daily-relationship": async () => (await import("./profiles/daily-relationship.js")).QUESTION_PROFILE,
  "daily-rest": async () => (await import("./profiles/daily-rest.js")).QUESTION_PROFILE,
});

export async function loadQuestionProfile(questionId) {
  const loader = QUESTION_PROFILE_REGISTRY[questionId];
  if (!loader) throw new Error(`Unknown QuestionProfile: ${questionId}`);
  return loader();
}
