#!/usr/bin/env node
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";
import { APP_VERSION, ARTIFACT_GENERATOR_VERSION } from "../src/config/version.js";
import { TarotData } from "../src/knowledge/legacy/index.js";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const GENERATED = "src/generated";
const TEXT_EXTENSIONS = new Set([
  ".css", ".html", ".js", ".json", ".md", ".mjs", ".py", ".svg", ".webmanifest",
]);
const OUTPUT_PATHS = Object.freeze([
  `${GENERATED}/card-catalog.js`,
  `${GENERATED}/question-catalog.js`,
  `${GENERATED}/knowledge-registry.js`,
  `${GENERATED}/knowledge-manifest.json`,
  `${GENERATED}/artifact-manifest.json`,
  `${GENERATED}/precache-manifest.js`,
]);

function normalizePath(value) {
  return value.split(path.sep).join("/").replace(/^\.\//, "");
}

function stableValue(value) {
  if (Array.isArray(value)) return value.map(stableValue);
  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.keys(value).sort().map((key) => [key, stableValue(value[key])]),
    );
  }
  return value;
}

function stableJson(value) {
  return `${JSON.stringify(stableValue(value), null, 2)}\n`;
}

function normalizeText(value) {
  return value.replace(/\r\n?/g, "\n");
}

function hashBytes(value) {
  return crypto.createHash("sha256").update(value).digest("hex");
}

function readNormalized(relativePath) {
  const absolutePath = path.join(ROOT, relativePath);
  const bytes = fs.readFileSync(absolutePath);
  return TEXT_EXTENSIONS.has(path.extname(relativePath).toLowerCase())
    ? Buffer.from(normalizeText(bytes.toString("utf8")), "utf8")
    : bytes;
}

function hashFile(relativePath) {
  return hashBytes(readNormalized(relativePath));
}

function walk(relativeDirectory) {
  const absoluteDirectory = path.join(ROOT, relativeDirectory);
  if (!fs.existsSync(absoluteDirectory)) return [];
  const result = [];
  for (const entry of fs.readdirSync(absoluteDirectory, { withFileTypes: true })) {
    const relativePath = normalizePath(path.join(relativeDirectory, entry.name));
    if (entry.isDirectory()) result.push(...walk(relativePath));
    else if (entry.isFile()) result.push(relativePath);
  }
  return result.sort();
}

function hashMap(paths) {
  return Object.fromEntries([...new Set(paths)].sort().map((item) => [item, hashFile(item)]));
}

function jsLiteral(value) {
  return JSON.stringify(value);
}

function buildCardCatalog() {
  return TarotData.deck.map((card) => ({
    id: card.id,
    name: card.name,
    en: card.en,
    arcana: card.arcana,
    suit: card.suit,
    element: card.element,
    accent: card.accent,
    keywords: [...card.keywords],
  }));
}

function buildQuestionCatalog() {
  return TarotData.categories.map((category) => ({
    id: category.id,
    name: category.name,
    icon: category.icon,
    accent: category.accent,
    questions: category.questions.map((question) => ({ id: question.id, text: question.text })),
  }));
}

function cardCatalogSource(cards) {
  return `// Generated by scripts/generate_artifacts.mjs v${ARTIFACT_GENERATOR_VERSION}. Do not edit.\nexport const CARD_CATALOG = Object.freeze(${jsLiteral(cards)});\n`;
}

function questionCatalogSource(categories) {
  return `// Generated by scripts/generate_artifacts.mjs v${ARTIFACT_GENERATOR_VERSION}. Do not edit.\nexport const QUESTION_CATALOG = Object.freeze(${jsLiteral(categories)});\n`;
}

function registrySource(cards, categories) {
  const cardIds = cards.map((item) => item.id);
  const questionIds = categories.flatMap((category) => category.questions.map((item) => item.id));
  const spreadIds = TarotData.spreads.map((item) => item.id);
  const cardEntries = cards.map((card) => {
    const profilePath = `src/knowledge/cards/${card.id}.js`;
    if (fs.existsSync(path.join(ROOT, profilePath))) {
      return `${JSON.stringify(card.id)}: async () => (await import("../knowledge/cards/${card.id}.js")).CARD_PROFILE`;
    }
    return `${JSON.stringify(card.id)}: async () => { const { majorCards, minorCards } = await import("../knowledge/legacy/build.js"); return [...majorCards, ...minorCards].find((item) => item.id === ${JSON.stringify(card.id)}) || null; }`;
  }).join(",\n  ");
  const questionEntries = questionIds.map((questionId) => {
    const profilePath = `src/knowledge/questions/profiles/${questionId}.js`;
    if (fs.existsSync(path.join(ROOT, profilePath))) {
      return `${JSON.stringify(questionId)}: async () => (await import("../knowledge/questions/profiles/${questionId}.js")).QUESTION_PROFILE`;
    }
    return `${JSON.stringify(questionId)}: async () => { const { CATEGORIES } = await import("../knowledge/legacy/questions.js"); return CATEGORIES.flatMap((category) => category.questions).find((item) => item.id === ${JSON.stringify(questionId)}) || null; }`;
  }).join(",\n  ");
  const spreadEntries = spreadIds.map((spreadId) => (
    `${JSON.stringify(spreadId)}: async () => { const { SPREADS } = await import("../knowledge/spreads/definitions.js"); return SPREADS.find((item) => item.id === ${JSON.stringify(spreadId)}) || null; }`
  )).join(",\n  ");
  return `// Generated by scripts/generate_artifacts.mjs v${ARTIFACT_GENERATOR_VERSION}. Do not edit.\nimport { CARD_CATALOG } from "./card-catalog.js";\nimport { QUESTION_CATALOG } from "./question-catalog.js";\n\nconst CARD_IDS = Object.freeze(${jsLiteral(cardIds)});\nconst QUESTION_IDS = Object.freeze(${jsLiteral(questionIds)});\nconst SPREAD_IDS = Object.freeze(${jsLiteral(spreadIds)});\n\nexport const CARD_REGISTRY = Object.freeze({\n  ${cardEntries}\n});\n\nexport const QUESTION_REGISTRY = Object.freeze({\n  ${questionEntries}\n});\n\nexport const SPREAD_REGISTRY = Object.freeze({\n  ${spreadEntries}\n});\n\nexport function assertKnowledgeCatalog(data) {\n  const actualCards = data.deck.map((item) => item.id);\n  const actualQuestions = data.categories.flatMap((category) => category.questions.map((item) => item.id));\n  const actualSpreads = data.spreads.map((item) => item.id);\n  if (JSON.stringify(actualCards) !== JSON.stringify(CARD_IDS)) throw new Error("Generated card catalog is stale.");\n  if (JSON.stringify(actualQuestions) !== JSON.stringify(QUESTION_IDS)) throw new Error("Generated question catalog is stale.");\n  if (JSON.stringify(actualSpreads) !== JSON.stringify(SPREAD_IDS)) throw new Error("Generated spread registry is stale.");\n  if (CARD_CATALOG.length !== CARD_IDS.length || QUESTION_CATALOG.length !== data.categories.length) {\n    throw new Error("Generated lightweight catalogs are incomplete.");\n  }\n  return true;\n}\n`;
}

function deckFiles(directory, extension, back, overrides = {}) {
  return [
    ...TarotData.deck.map((card) => `./${directory}/${card.id}.${overrides[card.id] || extension}`),
    `./${back}`,
  ];
}

function buildOutputs() {
  const cards = buildCardCatalog();
  const questions = buildQuestionCatalog();
  const outputs = new Map();
  outputs.set(`${GENERATED}/card-catalog.js`, cardCatalogSource(cards));
  outputs.set(`${GENERATED}/question-catalog.js`, questionCatalogSource(questions));
  outputs.set(`${GENERATED}/knowledge-registry.js`, registrySource(cards, questions));

  const knowledgeSources = [
    ...walk("src/knowledge"),
    ...walk("src/engine/legacy"),
  ].filter((item) => !item.startsWith(`${GENERATED}/`));
  const generatedKnowledge = [
    `${GENERATED}/card-catalog.js`,
    `${GENERATED}/question-catalog.js`,
    `${GENERATED}/knowledge-registry.js`,
  ];
  const knowledgeFiles = {
    ...hashMap(knowledgeSources),
    ...Object.fromEntries(generatedKnowledge.map((item) => [item, hashBytes(Buffer.from(outputs.get(item), "utf8"))])),
  };
  const knowledgeManifest = {
    schemaVersion: "1.0.0",
    generatorVersion: ARTIFACT_GENERATOR_VERSION,
    counts: { cards: cards.length, questions: questions.reduce((sum, item) => sum + item.questions.length, 0), spreads: TarotData.spreads.length },
    files: knowledgeFiles,
  };
  outputs.set(`${GENERATED}/knowledge-manifest.json`, stableJson(knowledgeManifest));

  const generatedBeforeArtifact = [...outputs.keys()];
  const runtimePaths = [
    "index.html", "manifest.webmanifest", "icon.svg", "sw.js",
    ...walk("src").filter((item) => !item.startsWith(`${GENERATED}/`)),
  ];
  const runtimeResources = {
    ...hashMap(runtimePaths),
    ...Object.fromEntries(generatedBeforeArtifact.map((item) => [item, hashBytes(Buffer.from(outputs.get(item), "utf8"))])),
  };
  const sourceSetHash = hashBytes(Buffer.from(stableJson(runtimeResources), "utf8"));
  const engineFiles = hashMap(walk("src/engine"));
  const engineManifestHash = hashBytes(Buffer.from(stableJson(engineFiles), "utf8"));
  const knowledgeManifestHash = hashBytes(Buffer.from(outputs.get(`${GENERATED}/knowledge-manifest.json`), "utf8"));
  const artifactManifest = {
    schemaVersion: "1.0.0",
    generatorVersion: ARTIFACT_GENERATOR_VERSION,
    generatorHash: hashFile("scripts/generate_artifacts.mjs"),
    appVersion: APP_VERSION,
    sourceSetHash,
    engineManifestHash,
    knowledgeManifestHash,
    modules: {
      cards: Object.fromEntries(cards.map((card) => {
        const profilePath = `src/knowledge/cards/${card.id}.js`;
        const legacyPath = card.arcana === "major"
          ? "src/knowledge/legacy/cards/major.js"
          : "src/knowledge/legacy/cards/minor.js";
        return [card.id, knowledgeFiles[profilePath] || knowledgeFiles[legacyPath]];
      })),
      questions: Object.fromEntries(questions.flatMap((category) => category.questions.map((question) => {
        const profilePath = `src/knowledge/questions/profiles/${question.id}.js`;
        return [question.id, knowledgeFiles[profilePath] || knowledgeFiles["src/knowledge/legacy/questions.js"]];
      }))),
      spreads: Object.fromEntries(TarotData.spreads.map((spread) => [spread.id, knowledgeFiles["src/knowledge/spreads/definitions.js"]])),
      vocabularies: hashMap(walk("src/knowledge/vocabularies")),
      schemas: hashMap(walk("src/knowledge/schemas")),
      positionOperators: hashMap(walk("src/knowledge/spreads/operators")),
    },
    runtimeResources,
  };
  outputs.set(`${GENERATED}/artifact-manifest.json`, stableJson(artifactManifest));
  const artifactManifestHash = hashBytes(Buffer.from(outputs.get(`${GENERATED}/artifact-manifest.json`), "utf8"));

  const requiredShell = [
    "./", "./index.html", "./manifest.webmanifest", "./icon.svg", "./sw.js",
    ...walk("src/styles").map((item) => `./${item}`),
    ...walk("src/app").map((item) => `./${item}`),
    ...walk("src/config").map((item) => `./${item}`),
    ...walk("src/core").map((item) => `./${item}`),
    ...walk("src/platform").map((item) => `./${item}`),
    ...walk("src/storage").map((item) => `./${item}`),
    ...walk("src/ui").map((item) => `./${item}`),
  ];
  const requiredKnowledge = [
    ...walk("src/knowledge").map((item) => `./${item}`),
    ...walk("src/engine").map((item) => `./${item}`),
    ...generatedBeforeArtifact.map((item) => `./${item}`),
    `./${GENERATED}/artifact-manifest.json`,
  ];
  const precache = {
    schemaVersion: "1.0.0",
    generatorVersion: ARTIFACT_GENERATOR_VERSION,
    releaseId: `${APP_VERSION}-${artifactManifestHash.slice(0, 12)}`,
    artifactManifestHash,
    required: {
      shell: [...new Set(requiredShell)].sort(),
      knowledge: [...new Set(requiredKnowledge)].sort(),
      startup: ["./manifest.webmanifest", "./icon.svg"],
    },
    optionalDecks: {
      rws: deckFiles("assets/rws", "jpg", "assets/rws/card-back-rws.jpg"),
      arnoult: deckFiles("assets/decks/arnoult", "png", "assets/decks/arnoult/card-back.jpg"),
      swiss: deckFiles("assets/decks/swiss-1jj", "jpg", "assets/decks/swiss-1jj/card-back.png", { "major-5": "png" }),
      piedmont: deckFiles("assets/decks/piedmont", "jpg", "assets/decks/piedmont/card-back.jpg"),
    },
  };
  const precacheSource = `// Generated by scripts/generate_artifacts.mjs v${ARTIFACT_GENERATOR_VERSION}. Do not edit.\n(() => {\n  if (typeof ServiceWorkerGlobalScope === "undefined" || !(self instanceof ServiceWorkerGlobalScope)) return;\n  Object.defineProperty(self, "__ASTRA_PRECACHE_MANIFEST__", {\n    value: Object.freeze(${jsLiteral(stableValue(precache))}),\n    writable: false,\n    configurable: false,\n  });\n})();\n`;
  outputs.set(`${GENERATED}/precache-manifest.js`, precacheSource);
  return { outputs, artifactManifestHash, precacheManifestHash: hashBytes(Buffer.from(precacheSource, "utf8")) };
}

function writeOutputs(outputs) {
  for (const [relativePath, content] of outputs) {
    const absolutePath = path.join(ROOT, relativePath);
    fs.mkdirSync(path.dirname(absolutePath), { recursive: true });
    fs.writeFileSync(absolutePath, normalizeText(content), "utf8");
  }
}

function checkOutputs(outputs) {
  const failures = [];
  for (const relativePath of OUTPUT_PATHS) {
    const expected = normalizeText(outputs.get(relativePath));
    const absolutePath = path.join(ROOT, relativePath);
    if (!fs.existsSync(absolutePath)) failures.push(`${relativePath}: missing`);
    else if (normalizeText(fs.readFileSync(absolutePath, "utf8")) !== expected) failures.push(`${relativePath}: stale`);
  }
  if (failures.length) {
    console.error(failures.join("\n"));
    return 1;
  }
  return 0;
}

const result = buildOutputs();
const checkMode = process.argv.includes("--check");
if (checkMode) {
  const status = checkOutputs(result.outputs);
  if (status) process.exitCode = status;
} else {
  writeOutputs(result.outputs);
}
console.log(JSON.stringify({
  mode: checkMode ? "check" : "write",
  generatorVersion: ARTIFACT_GENERATOR_VERSION,
  generated: OUTPUT_PATHS.length,
  artifactManifestHash: result.artifactManifestHash,
  precacheManifestHash: result.precacheManifestHash,
}));
