#!/usr/bin/env python3
"""Apply MOD-006B deterministic generated artifacts and manifest contracts."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def read(path: str) -> str:
    return (ROOT / path).read_text(encoding="utf-8")


def write(path: str, content: str) -> None:
    target = ROOT / path
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content.replace("\r\n", "\n"), encoding="utf-8", newline="\n")


def replace_once(source: str, old: str, new: str, label: str) -> str:
    count = source.count(old)
    if count != 1:
        raise RuntimeError(f"{label}: expected one match, found {count}")
    return source.replace(old, new, 1)


GITATTRIBUTES = """* text=auto
*.js text eol=lf
*.mjs text eol=lf
*.py text eol=lf
*.json text eol=lf
*.md text eol=lf
*.css text eol=lf
*.html text eol=lf
*.svg text eol=lf
*.webmanifest text eol=lf
*.jpg binary
*.jpeg binary
*.png binary
*.webp binary
"""

VERSION_JS = """export const APP_VERSION = "2.0.0-dev";
export const ARTIFACT_GENERATOR_VERSION = "1.0.0";
"""

GENERATOR = r'''#!/usr/bin/env node
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";
import { APP_VERSION, ARTIFACT_GENERATOR_VERSION } from "../src/config/version.js";
import { TarotData } from "../src/knowledge/legacy/index.js";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const GENERATED = "src/generated";
const TEXT_EXTENSIONS = new Set([
  ".css", ".html", ".js", ".json", ".md", ".mjs", ".py", ".svg", ".webmanifest",
]);
const OUTPUT_PATHS = Object.freeze([
  `${GENERATED}/card-catalog.js`,
  `${GENERATED}/question-catalog.js`,
  `${GENERATED}/knowledge-registry.js`,
  `${GENERATED}/knowledge-manifest.json`,
  `${GENERATED}/artifact-manifest.json`,
  `${GENERATED}/precache-manifest.js`,
]);

function normalizePath(value) {
  return value.split(path.sep).join("/").replace(/^\.\//, "");
}

function stableValue(value) {
  if (Array.isArray(value)) return value.map(stableValue);
  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.keys(value).sort().map((key) => [key, stableValue(value[key])]),
    );
  }
  return value;
}

function stableJson(value) {
  return `${JSON.stringify(stableValue(value), null, 2)}\n`;
}

function normalizeText(value) {
  return value.replace(/\r\n?/g, "\n");
}

function hashBytes(value) {
  return crypto.createHash("sha256").update(value).digest("hex");
}

function readNormalized(relativePath) {
  const absolutePath = path.join(ROOT, relativePath);
  const bytes = fs.readFileSync(absolutePath);
  return TEXT_EXTENSIONS.has(path.extname(relativePath).toLowerCase())
    ? Buffer.from(normalizeText(bytes.toString("utf8")), "utf8")
    : bytes;
}

function hashFile(relativePath) {
  return hashBytes(readNormalized(relativePath));
}

function walk(relativeDirectory) {
  const absoluteDirectory = path.join(ROOT, relativeDirectory);
  if (!fs.existsSync(absoluteDirectory)) return [];
  const result = [];
  for (const entry of fs.readdirSync(absoluteDirectory, { withFileTypes: true })) {
    const relativePath = normalizePath(path.join(relativeDirectory, entry.name));
    if (entry.isDirectory()) result.push(...walk(relativePath));
    else if (entry.isFile()) result.push(relativePath);
  }
  return result.sort();
}

function hashMap(paths) {
  return Object.fromEntries([...new Set(paths)].sort().map((item) => [item, hashFile(item)]));
}

function jsLiteral(value) {
  return JSON.stringify(value, null, 2);
}

function buildCardCatalog() {
  return TarotData.deck.map((card) => ({
    id: card.id,
    name: card.name,
    en: card.en,
    arcana: card.arcana,
    suit: card.suit,
    element: card.element,
    accent: card.accent,
    keywords: [...card.keywords],
  }));
}

function buildQuestionCatalog() {
  return TarotData.categories.map((category) => ({
    id: category.id,
    name: category.name,
    icon: category.icon,
    accent: category.accent,
    questions: category.questions.map((question) => ({ id: question.id, text: question.text })),
  }));
}

function cardCatalogSource(cards) {
  return `// Generated by scripts/generate_artifacts.mjs v${ARTIFACT_GENERATOR_VERSION}. Do not edit.\nexport const CARD_CATALOG = Object.freeze(${jsLiteral(cards)});\n`;
}

function questionCatalogSource(categories) {
  return `// Generated by scripts/generate_artifacts.mjs v${ARTIFACT_GENERATOR_VERSION}. Do not edit.\nexport const QUESTION_CATALOG = Object.freeze(${jsLiteral(categories)});\n`;
}

function registrySource(cards, categories) {
  const cardIds = cards.map((item) => item.id);
  const questionIds = categories.flatMap((category) => category.questions.map((item) => item.id));
  const spreadIds = TarotData.spreads.map((item) => item.id);
  return `// Generated by scripts/generate_artifacts.mjs v${ARTIFACT_GENERATOR_VERSION}. Do not edit.\nimport { CARD_CATALOG } from "./card-catalog.js";\nimport { QUESTION_CATALOG } from "./question-catalog.js";\n\nconst CARD_IDS = Object.freeze(${jsLiteral(cardIds)});\nconst QUESTION_IDS = Object.freeze(${jsLiteral(questionIds)});\nconst SPREAD_IDS = Object.freeze(${jsLiteral(spreadIds)});\n\nexport const CARD_REGISTRY = Object.freeze(Object.fromEntries(CARD_IDS.map((id) => [id, async () => {\n  const { majorCards, minorCards } = await import("../knowledge/legacy/build.js");\n  return [...majorCards, ...minorCards].find((card) => card.id === id) || null;\n}])));\n\nexport const QUESTION_REGISTRY = Object.freeze(Object.fromEntries(QUESTION_IDS.map((id) => [id, async () => {\n  const { CATEGORIES } = await import("../knowledge/legacy/questions.js");\n  return CATEGORIES.flatMap((category) => category.questions).find((question) => question.id === id) || null;\n}])));\n\nexport const SPREAD_REGISTRY = Object.freeze(Object.fromEntries(SPREAD_IDS.map((id) => [id, async () => {\n  const { SPREADS } = await import("../knowledge/spreads/definitions.js");\n  return SPREADS.find((spread) => spread.id === id) || null;\n}])));\n\nexport function assertKnowledgeCatalog(data) {\n  const actualCards = data.deck.map((item) => item.id);\n  const actualQuestions = data.categories.flatMap((category) => category.questions.map((item) => item.id));\n  const actualSpreads = data.spreads.map((item) => item.id);\n  if (JSON.stringify(actualCards) !== JSON.stringify(CARD_IDS)) throw new Error("Generated card catalog is stale.");\n  if (JSON.stringify(actualQuestions) !== JSON.stringify(QUESTION_IDS)) throw new Error("Generated question catalog is stale.");\n  if (JSON.stringify(actualSpreads) !== JSON.stringify(SPREAD_IDS)) throw new Error("Generated spread registry is stale.");\n  if (CARD_CATALOG.length !== CARD_IDS.length || QUESTION_CATALOG.length !== data.categories.length) {\n    throw new Error("Generated lightweight catalogs are incomplete.");\n  }\n  return true;\n}\n`;
}

function deckFiles(directory, extension, back, overrides = {}) {
  return [
    ...TarotData.deck.map((card) => `./${directory}/${card.id}.${overrides[card.id] || extension}`),
    `./${back}`,
  ];
}

function buildOutputs() {
  const cards = buildCardCatalog();
  const questions = buildQuestionCatalog();
  const outputs = new Map();
  outputs.set(`${GENERATED}/card-catalog.js`, cardCatalogSource(cards));
  outputs.set(`${GENERATED}/question-catalog.js`, questionCatalogSource(questions));
  outputs.set(`${GENERATED}/knowledge-registry.js`, registrySource(cards, questions));

  const knowledgeSources = [
    ...walk("src/knowledge"),
    ...walk("src/engine/legacy"),
  ].filter((item) => !item.startsWith(`${GENERATED}/`));
  const generatedKnowledge = [
    `${GENERATED}/card-catalog.js`,
    `${GENERATED}/question-catalog.js`,
    `${GENERATED}/knowledge-registry.js`,
  ];
  const knowledgeFiles = {
    ...hashMap(knowledgeSources),
    ...Object.fromEntries(generatedKnowledge.map((item) => [item, hashBytes(Buffer.from(outputs.get(item), "utf8"))])),
  };
  const knowledgeManifest = {
    schemaVersion: "1.0.0",
    generatorVersion: ARTIFACT_GENERATOR_VERSION,
    counts: { cards: cards.length, questions: questions.reduce((sum, item) => sum + item.questions.length, 0), spreads: TarotData.spreads.length },
    files: knowledgeFiles,
  };
  outputs.set(`${GENERATED}/knowledge-manifest.json`, stableJson(knowledgeManifest));

  const generatedBeforeArtifact = [...outputs.keys()];
  const runtimePaths = [
    "index.html", "manifest.webmanifest", "icon.svg", "sw.js",
    ...walk("src").filter((item) => !item.startsWith(`${GENERATED}/`)),
  ];
  const runtimeResources = {
    ...hashMap(runtimePaths),
    ...Object.fromEntries(generatedBeforeArtifact.map((item) => [item, hashBytes(Buffer.from(outputs.get(item), "utf8"))])),
  };
  const sourceSetHash = hashBytes(Buffer.from(stableJson(runtimeResources), "utf8"));
  const engineFiles = hashMap(walk("src/engine"));
  const engineManifestHash = hashBytes(Buffer.from(stableJson(engineFiles), "utf8"));
  const knowledgeManifestHash = hashBytes(Buffer.from(outputs.get(`${GENERATED}/knowledge-manifest.json`), "utf8"));
  const artifactManifest = {
    schemaVersion: "1.0.0",
    generatorVersion: ARTIFACT_GENERATOR_VERSION,
    generatorHash: hashFile("scripts/generate_artifacts.mjs"),
    appVersion: APP_VERSION,
    sourceSetHash,
    engineManifestHash,
    knowledgeManifestHash,
    modules: {
      cards: Object.fromEntries(cards.map((card) => [card.id, knowledgeFiles[card.arcana === "major" ? "src/knowledge/legacy/cards/major.js" : "src/knowledge/legacy/cards/minor.js"]])),
      questions: Object.fromEntries(questions.flatMap((category) => category.questions.map((question) => [question.id, knowledgeFiles["src/knowledge/legacy/questions.js"]]))),
      spreads: Object.fromEntries(TarotData.spreads.map((spread) => [spread.id, knowledgeFiles["src/knowledge/spreads/definitions.js"]])),
    },
    runtimeResources,
  };
  outputs.set(`${GENERATED}/artifact-manifest.json`, stableJson(artifactManifest));
  const artifactManifestHash = hashBytes(Buffer.from(outputs.get(`${GENERATED}/artifact-manifest.json`), "utf8"));

  const requiredShell = [
    "./", "./index.html", "./manifest.webmanifest", "./icon.svg", "./sw.js",
    ...walk("src/styles").map((item) => `./${item}`),
    ...walk("src/app").map((item) => `./${item}`),
    ...walk("src/config").map((item) => `./${item}`),
    ...walk("src/core").map((item) => `./${item}`),
    ...walk("src/platform").map((item) => `./${item}`),
    ...walk("src/storage").map((item) => `./${item}`),
  ];
  const requiredKnowledge = [
    ...walk("src/knowledge").map((item) => `./${item}`),
    ...walk("src/engine/legacy").map((item) => `./${item}`),
    ...generatedBeforeArtifact.map((item) => `./${item}`),
    `./${GENERATED}/artifact-manifest.json`,
  ];
  const precache = {
    schemaVersion: "1.0.0",
    generatorVersion: ARTIFACT_GENERATOR_VERSION,
    releaseId: `${APP_VERSION}-${artifactManifestHash.slice(0, 12)}`,
    artifactManifestHash,
    required: {
      shell: [...new Set(requiredShell)].sort(),
      knowledge: [...new Set(requiredKnowledge)].sort(),
      startup: ["./manifest.webmanifest", "./icon.svg"],
    },
    optionalDecks: {
      rws: deckFiles("assets/rws", "jpg", "assets/rws/card-back-rws.jpg"),
      arnoult: deckFiles("assets/decks/arnoult", "png", "assets/decks/arnoult/card-back.jpg"),
      swiss: deckFiles("assets/decks/swiss-1jj", "jpg", "assets/decks/swiss-1jj/card-back.png", { "major-5": "png" }),
      piedmont: deckFiles("assets/decks/piedmont", "jpg", "assets/decks/piedmont/card-back.jpg"),
    },
  };
  const precacheSource = `// Generated by scripts/generate_artifacts.mjs v${ARTIFACT_GENERATOR_VERSION}. Do not edit.\n(() => {\n  if (typeof ServiceWorkerGlobalScope === "undefined" || !(self instanceof ServiceWorkerGlobalScope)) return;\n  Object.defineProperty(self, "__ASTRA_PRECACHE_MANIFEST__", {\n    value: Object.freeze(${jsLiteral(stableValue(precache))}),\n    writable: false,\n    configurable: false,\n  });\n})();\n`;
  outputs.set(`${GENERATED}/precache-manifest.js`, precacheSource);
  return { outputs, artifactManifestHash, precacheManifestHash: hashBytes(Buffer.from(precacheSource, "utf8")) };
}

function writeOutputs(outputs) {
  for (const [relativePath, content] of outputs) {
    const absolutePath = path.join(ROOT, relativePath);
    fs.mkdirSync(path.dirname(absolutePath), { recursive: true });
    fs.writeFileSync(absolutePath, normalizeText(content), "utf8");
  }
}

function checkOutputs(outputs) {
  const failures = [];
  for (const relativePath of OUTPUT_PATHS) {
    const expected = normalizeText(outputs.get(relativePath));
    const absolutePath = path.join(ROOT, relativePath);
    if (!fs.existsSync(absolutePath)) failures.push(`${relativePath}: missing`);
    else if (normalizeText(fs.readFileSync(absolutePath, "utf8")) !== expected) failures.push(`${relativePath}: stale`);
  }
  if (failures.length) {
    console.error(failures.join("\n"));
    return 1;
  }
  return 0;
}

const result = buildOutputs();
const checkMode = process.argv.includes("--check");
if (checkMode) {
  const status = checkOutputs(result.outputs);
  if (status) process.exitCode = status;
} else {
  writeOutputs(result.outputs);
}
console.log(JSON.stringify({
  mode: checkMode ? "check" : "write",
  generatorVersion: ARTIFACT_GENERATOR_VERSION,
  generated: OUTPUT_PATHS.length,
  artifactManifestHash: result.artifactManifestHash,
  precacheManifestHash: result.precacheManifestHash,
}));
'''

GENERATED_TEST = r'''import assert from "node:assert/strict";
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import { fileURLToPath } from "node:url";
import { TarotData } from "../src/knowledge/legacy/index.js";
import { CARD_CATALOG } from "../src/generated/card-catalog.js";
import { QUESTION_CATALOG } from "../src/generated/question-catalog.js";
import { CARD_REGISTRY, QUESTION_REGISTRY, SPREAD_REGISTRY, assertKnowledgeCatalog } from "../src/generated/knowledge-registry.js";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const read = (relative) => fs.readFileSync(path.join(root, relative), "utf8");
const hash = (value) => crypto.createHash("sha256").update(value).digest("hex");
assert.equal(assertKnowledgeCatalog(TarotData), true);
assert.equal(CARD_CATALOG.length, 78);
assert.equal(QUESTION_CATALOG.reduce((sum, item) => sum + item.questions.length, 0), 42);
assert.equal(Object.keys(CARD_REGISTRY).length, 78);
assert.equal(Object.keys(QUESTION_REGISTRY).length, 42);
assert.equal(Object.keys(SPREAD_REGISTRY).length, 4);
assert.equal((await CARD_REGISTRY["major-0"]()).id, "major-0");
assert.equal((await QUESTION_REGISTRY[TarotData.categories[0].questions[0].id]()).id, TarotData.categories[0].questions[0].id);
assert.equal((await SPREAD_REGISTRY.single()).id, "single");

const artifactText = read("src/generated/artifact-manifest.json");
const artifact = JSON.parse(artifactText);
const knowledgeText = read("src/generated/knowledge-manifest.json");
assert.equal(artifact.knowledgeManifestHash, hash(knowledgeText.replace(/\r\n?/g, "\n")));
for (const forbidden of ["finalCommit", "commit", "precacheManifestHash", "artifactManifestHash"]) {
  assert.equal(Object.hasOwn(artifact, forbidden), false, `artifact manifest must not contain ${forbidden}`);
}
assert.equal(artifact.generatorVersion, "1.0.0");
assert.equal(Object.keys(artifact.modules.cards).length, 78);
assert.equal(Object.keys(artifact.modules.questions).length, 42);

const sandbox = { self: {}, ServiceWorkerGlobalScope: class ServiceWorkerGlobalScope {} };
sandbox.self = new sandbox.ServiceWorkerGlobalScope();
vm.createContext(sandbox);
vm.runInContext(read("src/generated/precache-manifest.js"), sandbox);
const precache = sandbox.self.__ASTRA_PRECACHE_MANIFEST__;
assert.ok(precache.releaseId.startsWith("2.0.0-dev-"));
assert.equal(precache.artifactManifestHash, hash(artifactText.replace(/\r\n?/g, "\n")));
assert.equal(precache.optionalDecks.rws.length, 79);
assert.equal(precache.optionalDecks.arnoult.length, 79);
assert.equal(precache.optionalDecks.swiss.length, 79);
assert.equal(precache.optionalDecks.piedmont.length, 79);
assert.equal("__ASTRA_PRECACHE_MANIFEST__" in globalThis, false);
console.log("MOD-006B generated artifact contract passed: catalogs, registries, DAG hashes, and classic precache manifest are deterministic.");
'''


def update_application(source: str) -> str:
    source = replace_once(
        source,
        'import { TarotData } from "../knowledge/legacy/index.js";\n',
        'import { TarotData } from "../knowledge/legacy/index.js";\nimport { assertKnowledgeCatalog } from "../generated/knowledge-registry.js";\n',
        "generated registry import",
    )
    return replace_once(
        source,
        "  const document = documentRef;\n",
        "  const document = documentRef;\n  assertKnowledgeCatalog(TarotData);\n",
        "generated catalog runtime assertion",
    )


def update_validate(source: str) -> str:
    anchor = '''        (
            "node-module-contract",
            [node, "tests/module_contract_test.mjs"],
        ),
'''
    addition = '''        (
            "generated-artifacts-check",
            [node, "scripts/generate_artifacts.mjs", "--check"],
        ),
        (
            "node-generated-artifacts-contract",
            [node, "tests/generated_artifacts_contract_test.mjs"],
        ),
'''
    return replace_once(source, anchor, addition + anchor, "generated validation steps")


def update_package(source: str) -> str:
    metadata = json.loads(source)
    scripts = metadata.setdefault("scripts", {})
    scripts["generate"] = "node scripts/generate_artifacts.mjs"
    scripts["check:generated"] = "node scripts/generate_artifacts.mjs --check"
    scripts["test:generated"] = "node tests/generated_artifacts_contract_test.mjs"
    return json.dumps(metadata, ensure_ascii=False, indent=2) + "\n"


def update_module_contract(source: str) -> str:
    source = replace_once(
        source,
        '  "automation/validate.py", "automation/quality-baseline.json", "docs/MODULE_MAP.md",\n',
        '  "automation/validate.py", "automation/quality-baseline.json", "docs/MODULE_MAP.md",\n  ".gitattributes", "scripts/generate_artifacts.mjs", "src/config/version.js",\n  "src/generated/card-catalog.js", "src/generated/question-catalog.js",\n  "src/generated/knowledge-registry.js", "src/generated/knowledge-manifest.json",\n  "src/generated/artifact-manifest.json", "src/generated/precache-manifest.js",\n  "tests/generated_artifacts_contract_test.mjs",\n',
        "generated required files",
    )
    source = replace_once(
        source,
        'console.log("MOD-006A module contract passed:',
        'console.log("MOD-006B module contract passed:',
        "module contract label",
    )
    return source


def write_progress() -> None:
    write("docs/PROGRESS.md", """# 项目开发进度

> 本文件是继续任务的唯一实时状态入口；任务定义以 `EXECUTION_CONTRACTS.md` 为准。

## 当前状态

| 项目 | 当前值 |
|---|---|
| 当前阶段 | Phase M：模块化基础 |
| 当前进行中任务 | `MOD-006C` 经典Service Worker策略与离线状态 |
| 最近完成任务 | `MOD-006B` 正式生成、规范哈希与manifest |
| 下一任务 | 无；Phase M连续执行中 |
| 阻塞项 | 无 |
| 工作分支 | `phase-m-completion` |
| Phase M状态 | `PARENT-IN-PROGRESS` |
| Phase 1状态 | `BLOCKED`，等待 `MOD-006D` |
| 最后更新时间 | 2026-07-31 |

## Phase M完成记录

| 任务 | 状态 | 产物/证据 |
|---|---|---|
| `MOD-001`–`MOD-003B` | `DONE` | 基线、CSS、ESM入口与基础模块已建立 |
| `MOD-004A` | `DONE` | `72b55c0e8b83f44b61b966eb39a849bf613b5436` |
| `MOD-004B` | `DONE` | `e1b2c8e73ad9c4e40cb5264aade7f60fe86618a9`；测试发现修复 `b31c2af465eb68466929d1c40938c409b60937d8` |
| `MOD-005` | `DONE` | `b03ca2602a36c4f96f2f2cf3c54d085db729116f`；固定复验 `01KYG9PHM5B2` |
| `MOD-006A` | `DONE` | `72cd7fa7ba05dab81b0f36a41c17d025002d8e29`；固定复验 `01KYG9PHM6AK2` |
| `MOD-006B` | `DONE` | 永久生成器、轻量目录、动态注册表、knowledge/artifact/precache清单和陈旧产物门禁 |
| `MOD-006C` | `IN_PROGRESS` | 下一步接线经典SW与离线状态 |
| `MOD-006D` | `BACKLOG` | 等待 `MOD-006C` |

## 当前不变量

- 根 `app.js`、`data.js`、`styles.css` 和旧运行桥保持删除。
- 78张牌、42个固定问题、1/3/5/10牌阵、公开ID、旧历史键和随机分布不变。
- 人工JS/CSS无超限技术债；不引入npm依赖、构建步骤或GitHub Actions。
- 人工源是唯一真相；`src/generated/` 只能由 `scripts/generate_artifacts.mjs` 重建。

## 当前任务：MOD-006C

按生成的 `src/generated/precache-manifest.js` 分类导航、版本化运行资源和牌组图片；建立 `APP-SHELL-READY`、`DEFAULT-DECK-READY`、`SELECTED-DECKS-READY` 状态，失败图片使用可访问占位且不重抽。
""")


def main() -> None:
    write(".gitattributes", GITATTRIBUTES)
    write("src/config/version.js", VERSION_JS)
    write("scripts/generate_artifacts.mjs", GENERATOR.lstrip())
    write("tests/generated_artifacts_contract_test.mjs", GENERATED_TEST.lstrip())
    write("src/app/application.js", update_application(read("src/app/application.js")))
    write("automation/validate.py", update_validate(read("automation/validate.py")))
    write("package.json", update_package(read("package.json")))
    write("tests/module_contract_test.mjs", update_module_contract(read("tests/module_contract_test.mjs")))
    write("docs/MODULE_MAP.md", read("docs/MODULE_MAP.md") + "\n\n## MOD-006B生成链\n\n人工源和运行资源经 `scripts/generate_artifacts.mjs` 依次生成轻量目录、动态注册表、knowledge清单、artifact manifest和经典SW预缓存清单。`--check` 以字节级比较阻止陈旧产物；artifact和precache遵守无自引用哈希图。\n")
    write("src/README.md", read("src/README.md") + "\n\n## 正式生成文件\n\n`src/generated/` 由 `node scripts/generate_artifacts.mjs` 生成并提交，禁止手工编辑。人工知识、引擎入口或活动资源变化后必须立即重建；`node scripts/generate_artifacts.mjs --check` 检查陈旧产物。\n")
    write("automation/README.md", read("automation/README.md") + "\n\nMOD-006B后baseline先执行生成物陈旧检查和生成契约。生成命令：`node scripts/generate_artifacts.mjs`；只读检查：`node scripts/generate_artifacts.mjs --check`。\n")
    write_progress()
    print("mod_006b_applied generator=1.0.0 outputs=6 runtime_catalog_assertion=enabled")


if __name__ == "__main__":
    main()
