export const CELTIC_POSITION_OPERATORS = Object.freeze([
  Object.freeze({ schemaVersion: "1.0.0", spreadId: "celtic", positionId: "present", selectableFacets: Object.freeze(["state", "relationship", "obstacle", "resource"]), tense: "present", subjectScope: "mixed", weight: 1.2, conditionality: "direct", actionTransform: "none", evidencePriority: "core", canSupportConclusion: true, canSupplyCounterEvidence: true }),
  Object.freeze({ schemaVersion: "1.0.0", spreadId: "celtic", positionId: "challenge", selectableFacets: Object.freeze(["obstacle", "boundary", "cause", "relationship"]), tense: "present", subjectScope: "mixed", weight: 1.2, conditionality: "corrective", actionTransform: "optional", evidencePriority: "core", canSupportConclusion: true, canSupplyCounterEvidence: true }),
  Object.freeze({ schemaVersion: "1.0.0", spreadId: "celtic", positionId: "above", selectableFacets: Object.freeze(["motivation", "reflection", "opportunity", "outcome"]), tense: "open", subjectScope: "self", weight: 0.95, conditionality: "contextual", actionTransform: "optional", evidencePriority: "secondary", canSupportConclusion: true, canSupplyCounterEvidence: false }),
  Object.freeze({ schemaVersion: "1.0.0", spreadId: "celtic", positionId: "below", selectableFacets: Object.freeze(["cause", "motivation", "reflection", "state"]), tense: "open", subjectScope: "self", weight: 1.05, conditionality: "contextual", actionTransform: "none", evidencePriority: "primary", canSupportConclusion: true, canSupplyCounterEvidence: true }),
  Object.freeze({ schemaVersion: "1.0.0", spreadId: "celtic", positionId: "past", selectableFacets: Object.freeze(["cause", "state", "motivation", "obstacle"]), tense: "past", subjectScope: "mixed", weight: 0.9, conditionality: "contextual", actionTransform: "none", evidencePriority: "secondary", canSupportConclusion: true, canSupplyCounterEvidence: true }),
  Object.freeze({ schemaVersion: "1.0.0", spreadId: "celtic", positionId: "future", selectableFacets: Object.freeze(["trend", "outcome", "opportunity", "boundary"]), tense: "near-future", subjectScope: "mixed", weight: 1, conditionality: "conditional", actionTransform: "none", evidencePriority: "primary", canSupportConclusion: true, canSupplyCounterEvidence: true }),
  Object.freeze({ schemaVersion: "1.0.0", spreadId: "celtic", positionId: "self", selectableFacets: Object.freeze(["state", "motivation", "action", "boundary", "resource"]), tense: "present", subjectScope: "self", weight: 1, conditionality: "contextual", actionTransform: "optional", evidencePriority: "primary", canSupportConclusion: true, canSupplyCounterEvidence: true }),
  Object.freeze({ schemaVersion: "1.0.0", spreadId: "celtic", positionId: "external", selectableFacets: Object.freeze(["relationship", "resource", "obstacle", "opportunity"]), tense: "present", subjectScope: "environment", weight: 0.9, conditionality: "contextual", actionTransform: "none", evidencePriority: "secondary", canSupportConclusion: true, canSupplyCounterEvidence: true }),
  Object.freeze({ schemaVersion: "1.0.0", spreadId: "celtic", positionId: "hopes", selectableFacets: Object.freeze(["motivation", "reflection", "obstacle", "opportunity"]), tense: "open", subjectScope: "self", weight: 0.8, conditionality: "contextual", actionTransform: "none", evidencePriority: "contextual", canSupportConclusion: false, canSupplyCounterEvidence: true }),
  Object.freeze({ schemaVersion: "1.0.0", spreadId: "celtic", positionId: "outcome", selectableFacets: Object.freeze(["outcome", "trend", "opportunity", "boundary"]), tense: "near-future", subjectScope: "mixed", weight: 1.1, conditionality: "conditional", actionTransform: "none", evidencePriority: "core", canSupportConclusion: true, canSupplyCounterEvidence: true }),
]);
